### ISSUE TITLE
Vague list of required dependencies and possible issues on code too

### ISSUE THREAD

**Issue by noxterr** [DandrewsDev/CS2VoiceData#1]
I'm opening an issue to address 2 things:
- a too-vague prerequisites/dependencies requirement;
- a possible issue in `decoder.go`;

To begin with the former, the list of _required dependencies_ isn't available or known. In the [reverse steam voice blog post](https://zhenyangli.me/posts/reversing-steam-voice-codec/) there are references to celt, opus (opus plc decoder), and Steam itself. However, it has not been clear what is the correct list of dependencies to have.

Furthermore, does CS2 have to be installed? Has it to be added/referenced to $PATH? What dependencies (audio-wise) are required? I had to install `brew install pkg-config` as I am on MacOS, hence does this work here too or am I required to do it on Windows only?

As a reference, I'm leaving [this](https://github.com/saiko-tech/csgo-demo-voice-capture-example) old repository that was well documented, at least for me.

For the issue on the file, in `decoder.go`, I can see there is an undefined function:
```go
func (d *OpusDecoder) decodeLoss(samples uint16) ([]float32, error) {
    loss := min(samples, 10) // undeclared name: min
    /* ... */
}
```

Are you trying to reference another function (I cannot find any) or are you using that from another imported module? I can open a PR about it to fix this.
I also wanted to open a PR about some improvements to the code, I'll wait for an answer here then help out. This repo has great value and I want to help improve it

**Comment by DandrewsDev** [comment]
Alright so starting off with the requirements. Pretty much everything that's required to run this is part of the go.mod file and is installed by doing a `go get`. I have that listed in the readme for getting set up.

You don't need to have CS2 or Steam installed at all. You also don't need to copy any of the files like `vaudio_celt_client.so` which was required for the CSGO projects that accomplished this same thing.

This project does have a dependency on lib opus, which is easy to install on windows/mac/linux. Heres a link with the info needed to install that.
https://github.com/hraban/opus/tree/v2#build--installation

I'll be adding some info to the readme soon to help include information about the lib opus requirement and how to install it.

As for the issue you noted with the decoder. 
The min function is a builtin golang function https://pkg.go.dev/builtin#min
Perhaps you're on an older version of golang?

**Comment by DandrewsDev** [comment]
Updated readme with info about the opus dependency, as well as the use of go.mod and pulling those dependencies. 

Closing this for now, feel free to open up a new issue if needed.
